<script setup>
import { computed, ref } from 'vue'
import { useAdminSession } from './stores/session'
import { adminLogin, adminLogout } from './api'
const session = useAdminSession(); const page = ref('overview'); const loginForm = ref({ username: '', password: '', otp: '' }); const error = ref(''); const busy = ref(false); const needsOtp = ref(false)
const menus = [{ id:'overview', label:'运行概览', icon:'⌂' }, { id:'users', label:'用户治理', icon:'◌' }, { id:'releases', label:'版本发布', icon:'↥' }, { id:'admins', label:'管理员与角色', icon:'◇' }, { id:'audit', label:'审计日志', icon:'≡' }]
const current = computed(() => menus.find(m => m.id === page.value) || menus[0])
async function submitLogin() { busy.value = true; error.value = ''; try { const result = await adminLogin(loginForm.value); if (result?.data?.otpRequired) needsOtp.value = true; else if (result?.data?.accessToken) session.login(result.data.accessToken, result.data.username) ; else error.value = result?.message || '登录失败' } catch (e) { error.value = e?.response?.data?.message || '服务暂时不可用' } finally { busy.value = false } }
async function logout() { try { await adminLogout() } finally { session.logout() } }
</script>
<template>
  <div v-if="!session.loggedIn" class="auth-page"><div class="auth-glow"></div><section class="login-panel"><div class="brand-mark">LY</div><div class="eyebrow">LIANYU OPERATIONS</div><h1>管理中枢</h1><p>让每一次发布与治理，都有迹可循。</p><form @submit.prevent="submitLogin"><label>管理员账号<input v-model="loginForm.username" autocomplete="username" placeholder="输入账号" /></label><label>密码<input v-model="loginForm.password" type="password" autocomplete="current-password" placeholder="输入密码" /></label><label v-if="needsOtp">动态验证码<input v-model="loginForm.otp" inputmode="numeric" placeholder="6 位验证码" /></label><div v-if="error" class="form-error">{{ error }}</div><button class="primary-button" :disabled="busy">{{ busy ? '正在验证…' : '进入管理中枢' }}</button></form><small>仅限受信管理员使用 · 会话将自动保护</small></section></div>
  <div v-else class="admin-shell"><header class="titlebar"><div class="titlebar-brand"><span class="brand-dot">LY</span><span>LianYu Admin</span><i>管理中枢</i></div><div class="window-actions"><button @click="window.adminWindow?.minimize()">−</button><button @click="window.adminWindow?.toggleMaximize()">□</button><button class="close" @click="window.adminWindow?.close()">×</button></div></header><aside class="sidebar"><div class="side-caption">WORKSPACE</div><button v-for="item in menus" :key="item.id" :class="['menu-item',{active:page===item.id}]" @click="page=item.id"><span>{{ item.icon }}</span>{{ item.label }}</button><div class="sidebar-foot"><div class="status-line"><b></b> API 在线</div><button class="logout" @click="logout">退出管理员会话</button></div></aside><main class="workspace"><div class="workspace-head"><div><div class="eyebrow">{{ current.id.toUpperCase() }}</div><h2>{{ current.label }}</h2></div><div class="head-meta">{{ session.username }} <span class="avatar">{{ session.username.slice(0,1).toUpperCase() }}</span></div></div><section v-if="page==='overview'" class="overview"><div class="signal-row"><div><small>当前环境</small><strong>生产服务</strong><span class="pill success">运行正常</span></div><div><small>最新客户端</small><strong>v0.2.363</strong><span class="muted">stable · 已发布</span></div><div><small>待处理事项</small><strong>12</strong><span class="muted">需要关注</span></div></div><div class="section-title"><h3>最近活动</h3><span>过去 24 小时</span></div><div class="activity-table"><div class="table-head"><span>事件</span><span>操作者</span><span>结果</span><span>时间</span></div><div v-for="row in [{e:'客户端版本发布 v0.2.363',a:'system',r:'已完成',t:'今天 09:42'},{e:'公告「服务维护通知」上线',a:session.username,r:'已完成',t:'昨天 18:10'},{e:'用户会话撤销 · #10482',a:session.username,r:'已完成',t:'昨天 16:54'}]" class="table-row"><span>{{row.e}}</span><span class="muted">{{row.a}}</span><span class="pill success">{{row.r}}</span><span class="muted">{{row.t}}</span></div></div></section><section v-else class="empty-section"><div class="section-title"><h3>{{ current.label }}</h3><button class="primary-button small">新增记录</button></div><div class="empty-box"><span>{{ current.icon }}</span><strong>{{ current.label }}工作区已就绪</strong><p>接入服务后，这里会显示可筛选、可审计的真实数据。</p></div></section></main></div>
</template>
