-- 团队公用 DEFAULT 10-key 池（Jasypt 密文，非明文）
-- 解密依赖 .env 中团队统一的 LIANYU_MASTER_KEY（与加密时一致，key_version=v1）
-- 新同事 clone 后：填好 .env 的 LIANYU_MASTER_KEY + docker compose up，无需自备 10 个 sk

UPDATE api_key_vault SET api_key_encrypted='QQJQ7GX95MbyQBBYXZHI4eZ6xteRod8wFf0Ozh5uyjNGReoiAq+Ncu3xtmQXG3CsF3AHx9WNW4drCdxYSNrgYdWfrpHZYzKl2fLM38FYsWzxfFoGWTDzP0TX+0NxDPv1', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-1' WHERE id=1 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='01Clo1iG3XIZ51+titnn9zp5ZWnQvNBRm8xfGuHMx4ebxAb1O8BKyVp72z52XRLJp7YrWY51N6mmj0UaaqkDtCuaCR5ubR9N9/BBGbyyre5EogpgqbdyOnfY6wJKo41H', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-2' WHERE id=2 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='31efcCdCkO2vOanhGU1mf/lZRe4wWlANvyt7NMaugLIDW13K8mEYcRAAknJ+IGSGIa11XkmN6vkWxLJPoeVaspUPB2v+O9GHs8BQro8RJAcLQelbeppnUAvhBfGe+5rt', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-3' WHERE id=3 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='7vX0eyfDuXC3hE4qui/445RWNlMlnoyYEgMssMWfenDZOzd9Sgo6F9kMU791sWk40X8lA0EkCLtkJOMTSdi09mVuf5aCHxzpZXmalbvtRYzX9uEb+naXmljcqKoROU96', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-4' WHERE id=4 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='mcBe7E/v66+Z66ByJMnqeZAxS8X5umeQwvKwwY4x3YyWHY/rGaxC9P3+lxoGnSd+mwwp5klSWyKU9boej3VOWDmMTH38+0RzWe3qFnGeXXsLQ/KIMjJAmIQKaDAxEExy', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-5' WHERE id=5 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='+crNRRcbNqRDxGnQFTXd9ixmQJFVERSUv4F2IlP+pTxyXmGHmRA2pZinFrsFJ9kgmtWq5gHZoQ9NAgtb28WHS9DLmHuxtImXoagtt/v3yRhcnmgCrDJOs3UqIZpwFn8s', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-6' WHERE id=6 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='jxCsMW8G4gygbrPAQoTmFFse6P573IrmadIBKhJXhq/HSaGfzT2xGy4Dpi0BRlmL72clZe7oN9xGDttTFcOwlJ/cfGneHAEIv2z+8JUNV+1sh2g7wq5xButuIoD7xXjf', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-7' WHERE id=7 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='Mr4hWiBu7xwWojqH9BlR4AQHSNziK+tHcc/jylPYP7vB/UDgPLEJlSIITuN3M6o1hSkijkjLE71Lpi1+iaQR9sfc7jLDjW4nLTE4ouQZola75mmNifwJd7UOA3jua2y9', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-8' WHERE id=8 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='uyAJ/nn3ea9Mb4jKmwHvZbI5uRKI+gYsVy8TEv0cqxRLNOUQbGo9Ohp70SnlPAzLadGSoxjS/iMEucX1fH+Evg/SGUG96SmAY53qV0e2+RrD50wL77PW2mmqSNbrynED', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-9' WHERE id=9 AND vault_scope='DEFAULT';
UPDATE api_key_vault SET api_key_encrypted='Q4OuRA8aHrWYtTai2GnpVAtmb0TqOxlYzk03harAZUeZdQ8v4OLRaY+CCyqVJGWIeWS9VCDWBBB2M0Bhu4H2Xb2yXOcFRLb9CTMVZCT+R+O8pFh1UD5JzVp5Z2ftIq5V', key_version='v1', enabled=1, base_url='https://clove.dpdns.org', model_default='deepseek-v4-flash', remark='default-pool-10' WHERE id=10 AND vault_scope='DEFAULT';
