package com.lianyu.service.relationship;

public enum RelationshipEventType {
    USER_VULNERABLE_SHARE,
    USER_WARM_RESPONSE,
    USER_DISMISSIVE_RESPONSE,
    USER_BROKE_PROMISE,
    ASSISTANT_VULNERABLE_REPLY,
    MISUNDERSTANDING_TRIGGERED,
    REPAIR_ATTEMPT,
    REPAIR_SUCCESS,
    SPECIAL_NICKNAME_CREATED,
    RITUAL_ESTABLISHED
}
